[package]
description = "Support for rust-i18n crate."
edition = "2021"
license = "MIT"
name = "rust-i18n-support"
version = "0.1.1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3"
lazy_static = "1.4.0"
proc-macro2 = "1.0"
quote = "1.0.2"
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
syn = "1.0.82"

[lib]
proc-macro = true
