[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
build = "build.rs"
categories = ["i18n", "yml", "compile-time", "localization", "internationalization"]
description = "Rust I18n is use Rust codegen for load YAML file storage translations on compile time, and give you a t! macro for simply get translation texts."
edition = "2018"
keywords = ["i18n", "localization", "internationalization"]
license = "MIT"
name = "rust-i18n"
readme = "README.md"
repository = "https://github.com/longbridgeapp/rust-i18n"
version = "0.1.4-alpha.0"

[dependencies]
glob = "0.3"
lazy_static = "1.4.0"
serde_json = "1"
serde_yaml = "0.8"

[build-dependencies]
glob = "0.3.0"
proc-macro2 = "1.0"
quote = "1.0.2"
regex = "1.3.1"
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
