[package]
edition = "2021"
name = "rust-i18n-example"
version = "0.1.0"

[dependencies]
example-base = {path = "../crates/example-base"}
lazy_static = "1.4"
rust-i18n = {path = "../../../../rust-i18n"}
